### ISSUE TITLE
could not detect network

### ISSUE THREAD

**Issue by davidqw** [tornadocash/tornado-root-updater#1]
Hello guys, 
     When i executive docker-compose up and get the "noNetwork" error below. How could I setup the network in env file, thanks

> Getting events for blocks 11475128 to 11567309
> app_1    | Submitting tree update with 60 deposits and 60 withdrawals
> app_1    | Tx failed... Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.0.13)
> app_1    |     at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
> app_1    |     at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
> app_1    |     at JsonRpcProvider.<anonymous> (/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:399:54)
> app_1    |     at step (/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:46:23)
> app_1    |     at Object.throw (/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:27:53)
> app_1    |     at rejected (/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:65) {
> app_1    |   reason: 'could not detect network',
> app_1    |   code: 'NETWORK_ERROR',
> app_1    |   event: 'noNetwork'
> app_1    | }
> app_1    | Retrying

**Comment by pertsev** [comment]
Hello.

You have to have [`.env`](https://github.com/tornadocash/tornado-root-updater/blob/master/.env.example) file (without `.example` postfix). It's used by [`docker-compose.yml`](https://github.com/tornadocash/tornado-root-updater/blob/master/docker-compose.yml#L8) file.

Also make sure you specified a correct `RPC_URL` in the `.env`.

**Comment by davidqw** [comment]
I tried to setup the .env file as below, add the NET_ID and RPC_URL, however it is not work

NET_ID = 1
RPC_URL = ws://my_ip_address:8546 (replaced by http_rpc_url and alchemy, either of them get the same result)



> Hello.
> 
> You have to have [`.env`](https://github.com/tornadocash/tornado-root-updater/blob/master/.env.example) file (without `.example` postfix). It's used by [`docker-compose.yml`](https://github.com/tornadocash/tornado-root-updater/blob/master/docker-compose.yml#L8) file.
> 
> Also make sure you specified a correct `RPC_URL` in the `.env`.

**Comment by pertsev** [comment]
You don't need the `NET_ID`. Just `RPC_URL` without spaces (http should work) 

Like this

`RPC_URL=https://mainnet.infura.io/v3/...`
