### ISSUE TITLE
Cannot connect to redis URL

### ISSUE THREAD

**Issue by jasonhuan** [tornadocash/tornado-root-updater#2]
In the .env file, after putting in a valid RPC endpoint and private key, it gives this error:
`[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379`

It seems like the redis URL provided in `.env.example` isn't working
`REDIS_URL=redis://127.0.0.1:6379`

Is there an alternative?

**Comment by pertsev** [comment]
If you want to run not as a docker container you need to run the Redis service first.

it's better to use docker-compose. You can see a step by step guide [here](https://github.com/tornadocash/tornado-root-updater#usage-with-docker)

**Comment by jasonhuan** [comment]
Apologies, I didn't read the part about installing redis.
